/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bravest_ptt_efastquery_utils_JNIUtils */

#ifndef _Included_bravest_ptt_efastquery_utils_JNIUtils
#define _Included_bravest_ptt_efastquery_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bravest_ptt_efastquery_utils_JNIUtils
 * Method:    getKey
 * Signature: (Landroid/content/res/AssetManager;)Lbravest/ptt/efastquery/entity/word/Key;
 */
JNIEXPORT jobject JNICALL Java_bravest_ptt_efastquery_utils_JNIUtils_getKey
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
