/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bravest_ptt_efastquery_data_TranslateEngine */

#ifndef _Included_bravest_ptt_efastquery_data_TranslateEngine
#define _Included_bravest_ptt_efastquery_data_TranslateEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef bravest_ptt_efastquery_data_TranslateEngine_CONNECTION_TIME_OUT
#define bravest_ptt_efastquery_data_TranslateEngine_CONNECTION_TIME_OUT 3000L
/*
 * Class:     bravest_ptt_efastquery_data_TranslateEngine
 * Method:    getKeyIdFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_bravest_ptt_efastquery_data_TranslateEngine_getKey
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
